# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Personal site of Qinyi Yao
email: yqy980210@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This website is currently under construction, you may subscribe to the RSS feed for further update.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yqy.design" # the base hostname & protocol for your site
twitter_username: 
github_username:  yqy980210

# Build settings
markdown: kramdown
